version: '3'

services:
  
  # Interface graphique d'administration
  Portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - DATA:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Essai
  
  Nginx:
    image: easylinux/kubernetes:nginx
    ports:
      - 8081:80
    
  NextDb:
    image: easylinux/mariadb:10.3.17
    volumes:
      - NEXTDB:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=Nextcloud
      - MYSQL_USER=Nextcloud
      - MYSQL_PASSWORD=Secr3t
 
  NextApp:
    image: nextcloud
    volumes:
      - NEXTAPP:/var/www/html
    ports:
      - 8086:80
    depends_on:
      - NextDb

networks:
  Essai: 

volumes:
  DATA:
  WORDDB:
  WORDAPP:
  NEXTDB:
  NEXTAPP:
